### ISSUE TITLE
multi-thread bug

### ISSUE THREAD

**Issue by burymyname** [R-Fuzz/jigsaw#1]
Hi, I found that jigsaw can run with single thread but has bug in multi-thread mode.
For example, I run with command `rgd 1 0 ./testcase`, it can run normally
If you run like this `rgd 2 0 ./testcase`, it will trigger segfault:
```
number of threads 2
 pin_core_start 0
Loading In progress 2all count is 1104, drop count is 0 record number is 1069 allexpr is 42109
[1]    41806 segmentation fault (core dumped) rgd 2 0 ./testcases
```

I use gdb to debug found it may be a data race bug
```
Reading symbols from /jigsaw/build/rgd...
[New LWP 41807]
[New LWP 41808]
[New LWP 41806]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/jigsaw/build/rgd 2 0 ./testcases'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  tcmalloc::SLL_Next (t=0x0) at src/linked_list.h:45
45        return *(reinterpret_cast<void**>(t));
[Current thread is 1 (Thread 0x7f28a877a700 (LWP 41807))]
(gdb) bt
#0  tcmalloc::SLL_Next (t=0x0) at src/linked_list.h:45
#1  tcmalloc::SLL_PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=16, head=0x55b57c3e83a0) at src/linked_list.h:88
#2  tcmalloc::ThreadCache::FreeList::PopRange (end=<synthetic pointer>, start=<synthetic pointer>, N=16, this=0x55b57c3e83a0) at src/thread_cache.h:238
#3  tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x55b57c3e8080, src=src@entry=0x55b57c3e83a0, cl=<optimized out>, N=16, N@entry=32) at src/thread_cache.cc:206
#4  0x00007f28aea09c8c in tcmalloc::ThreadCache::ListTooLong (this=0x55b57c3e8080, list=0x55b57c3e83a0, cl=<optimized out>) at src/thread_cache.cc:164
#5  0x000055b57ac8fb74 in __gnu_cxx::new_allocator<rgd::JitRequest*>::deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/7/ext/new_allocator.h:125
#6  std::allocator_traits<std::allocator<rgd::JitRequest*> >::deallocate (__a=..., __n=64, __p=<optimized out>) at /usr/include/c++/7/bits/alloc_traits.h:462
#7  std::_Deque_base<rgd::JitRequest*, std::allocator<rgd::JitRequest*> >::_M_deallocate_node (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/7/bits/stl_deque.h:609
#8  std::_Deque_base<rgd::JitRequest*, std::allocator<rgd::JitRequest*> >::_M_destroy_nodes (this=0x7f28a8779900, __nfinish=0x55b58da4b260, __nstart=<optimized out>)
    at /usr/include/c++/7/bits/stl_deque.h:743
#9  std::_Deque_base<rgd::JitRequest*, std::allocator<rgd::JitRequest*> >::~_Deque_base (this=0x7f28a8779900, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_deque.h:665
#10 0x000055b57ac83b08 in std::deque<rgd::JitRequest*, std::allocator<rgd::JitRequest*> >::~deque (this=0x7f28a8779900, __in_chrg=<optimized out>)
    at /usr/include/c++/7/bits/stl_deque.h:1045
#11 toDNF (req=<optimized out>, res=std::deque with 1 element = {...}) at /jigsaw/rgd.cc:1285
#12 0x000055b57ac850b3 in parseRequest (threadId=<error reading variable: Cannot access memory at address 0xfffffffffffffe78>, funcCache=..., Python Exception <class 'gdb.error'> value has been optimized out:
tasks=<synthetic pointer>, cmd=...,
    opti=<optimized out>) at /jigsaw/rgd.cc:1558
#13 sendLocalCmd (opti=opti@entry=true, cmd=std::shared_ptr<rgd::JitCmdv2> (use count 3, weak count 0) = {...}, i=i@entry=0, funcCache=...,
    rgd_solution=rgd_solution@entry=0x7f28a8779cd0, opti_solution=opti_solution@entry=0x7f28a8779d10, hint_solution=0x7f28a8779d50, st=0x7f28a8779ca8, iter=0x7f28a8779cb0, fname="")
    at /home/fuzz/hwz/personal/jigsaw/rgd.cc:1678
#14 0x000055b57ac86fea in rgdTask (threadarg=0x7ffe95bc3b40) at /jigsaw/rgd.cc:1826
#15 0x00007f28aa5636db in start_thread (arg=0x7f28a877a700) at pthread_create.c:463
#16 0x00007f28a952e61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by chenju2k6** [comment]
Thanks for the report. Is it possible to send me the `testcase` that you are testing?

**Comment by burymyname** [comment]
There are 2 [constraints](https://github.com/burymyname/seeds/tree/master/jigsaw) provided by jigsaw

**Comment by chenju2k6** [comment]
Thanks. I can reproduce the bug.

**Comment by chenju2k6** [comment]
The issue is due to a bug in the constraints cache which results in a memory corruption under multi-threaded execution. I just pushed the patch (commit fb37d55a0c94ceb55b58bd899e1b375f1d96fe5).  Thanks!
